apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-serving.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "model-serving.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "model-serving.selectorLabels" . | nindent 4 }}

